apiVersion: v1
kind: Service
metadata:
  name: docker-go
  namespace: illuminati
  labels:
    {{- include "illuminati-email-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "illuminati-email-service.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8080
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http